// This file was autogenerated by `compile.py` and will be overwritten on subsequent runs.
#include "base.h"
#include "Code.h"

uint8_t DA;

void main_init() {
    DA = 2;
    Apply();
    delay(waitTime);
    Reset();
    writeData(DA);
    setwriteAddr(1);
    Apply();
    delay(waitTime);
    Reset();
    DA = 2;
    Apply();
    delay(waitTime);
    Reset();
    writeData(DA);
    setwriteAddr(2);
    Apply();
    delay(waitTime);
    Reset();
    setwriteAddr(0);
    writeAddr(0b101001);
    Apply();
    delay(waitTime);
    Reset();
    setreadAddr(0);
    Apply();
    delay(waitTime);
    printData();
    Reset();
    setreadAddr(0);
    setwriteAddr(3);
    Apply();
    delay(waitTime);
    Reset();
    setreadAddr(0);
    setwriteAddr(1);
    Apply();
    delay(waitTime);
    Reset();
}

void main_tick() {
}
